name: complie-rust
run-name: ${{ github.actor }} is compling binaries for Rust
on: [push]
jobs:
  compile-for-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: sudo apt-get update
      - run: rustup component add rust-std
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo test
      - run: cargo fmt
      - run: cargo build --target=wasm32-unknown-unknown --release
      - run: ls -al target/
      - run: rustup target install x86_64-unknown-linux-gnu
      - run: sudo apt install gcc-multilib
      - run: cargo build --target=x86_64-unknown-linux-gnu
      - run: ls -al target/
      - run: rustup target install aarch64-unknown-linux-gnu
      - run: sudo apt-get install gcc-aarch64-linux-gnu
      - run: echo "[target.aarch64-unknown-linux-gnu]" > ~/.cargo/config.toml
      - run: echo "linker = \"aarch64-linux-gnu-gcc\"" >> ~/.cargo/config.toml
      - run: cargo build --target=aarch64-unknown-linux-gnu
      - run: ls -al target/
      - run: pwd
      - name: publish a release
        uses: softprops/action-gh-release@v1
        run: ls -al target/
        run: ls -al
        with:
          files: | 
            /home/runner/work/edgeless-functions/edgeless-functions/target/*
            /home/runner/work/edgeless-functions/edgeless-functions/target/aarch64*
            /home/runner/work/edgeless-functions/edgeless-functions/target/wasm32*
            /home/runner/work/edgeless-functions/edgeless-functions/target/x86_64*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
    


