name: complie-rust
run-name: ${{ github.actor }} is compling binaries for Rust
on: [push]
jobs:
  compile-for-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: rustup component add rust-std
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo test
      - run: cargo fmt
      - run: cargo build --target=wasm32-unknown-unknown --release
      - run: ls -al target/
      - run: rustup target install i686-unknown-linux-gnu
      - run: apt install gcc-multilib
      - run: cargo build --target=i686-unknown-linux-gnu
      - run: ls -al

